/*
 * سجل الملكية (R10) — المالك الوحيد لكل أصل وكل معلومة
 * (P2, I4, G5). المحتوى: التجمّعات الخمسة والعشرون
 * (DOMAIN_MODEL.md Section 1) وتعيين الجداول الكامل
 * (aggregate-table-mapping.csv، 234 جدولًا). كل جدول
 * مُسند إلى تجمّع واحد بالضبط. الملكية إعلان هنا
 * ويُنفَّذ عبر نطاق الأدلة (D3). مرحلة الأولى تسجيل
 * هيكلي فقط — بلا منطق تحقق.
 */
import { AggregateDefinition, AggregateTable, AggregateTier } from './types';
import { ConstitutionalRegistry } from './registry';

function aggregate(
  id: AggregateDefinition['id'],
  name: string,
  tier: AggregateTier,
  purpose: string,
  businessOwner: string,
  rootEntity: string,
  responsibility: string,
  boundary: string,
): AggregateDefinition {
  return { id, name, tier, purpose, businessOwner, rootEntity, responsibility, boundary };
}

function table(
  aggregate: AggregateTable['aggregate'],
  schema: string,
  table: string,
  ownership: string,
  classification: AggregateTable['classification'],
): AggregateTable {
  return { aggregate, schema, table, ownership, classification };
}

export const AGGREGATES: ReadonlyArray<AggregateDefinition> = [
  aggregate('A01', 'Application', 'Core', 'The central ethics-governance work item; carries research information through review, decision, condition, approval, closure, archive.', 'Research Ethics Governance', 'Application', 'RULE 11 terminal-state derivation; submission integrity; version immutability; consent linkage', 'Starts at application preparation; ends at terminal state (REJECTED/WITHDRAWN/ARCHIVED) or handoff to Research Lifecycle'),
  aggregate('A02', 'Condition', 'Core', 'A requirement issued under a governance decision; its resolution and evidence.', 'Research Ethics Governance', 'ApplicationCondition', 'RULE 12 evidence-DELETE four-factor matrix; condition lifecycle (OPEN/MET/NOT_MET/WAIVED)', 'Condition issuance → resolution, waiver, or supersession'),
  aggregate('A03', 'ResearchProject', 'Core', 'The real-world research activity being governed.', 'Research Governance Authority', 'Project', 'Research metadata integrity; site/team/funding coherence', 'Project proposal → active → closed/archived'),
  aggregate('A04', 'Committee', 'Core', 'The authorized governance body and its membership.', 'Research Ethics Committee', 'Committee', 'Member term validity; conflict disclosure; committee type authority', 'Committee constitution → review → renewal/retirement'),
  aggregate('A05', 'Meeting', 'Core', 'Committee deliberation and voting.', 'Research Ethics Committee', 'CommitteeMeeting', 'Quorum before decision; votes recorded; minutes retained', 'Meeting call → quorum → decision record'),
  aggregate('A06', 'Review', 'Core', 'Reviewer assessment of submitted material.', 'Research Ethics Committee', 'ReviewAssignment', 'Reviewer SHALL have an assignment before an outcome; conflict disclosure; score/answer traceability', 'Assignment → review completion → contribution to decision'),
  aggregate('A07', 'Approval', 'Core', 'Authorized permission and its formal certificate.', 'Research Ethics Governance', 'ApprovalCertificate', 'Approval SHALL derive from an authorized decision; certificate validity', 'Approval granted → closed/withdrawn/superseded/archived'),
  aggregate('A08', 'Accreditation', 'Supporting', 'Institutional/committee maturity and readiness.', 'Research Governance Authority', 'AccreditationAssessment', 'Assessment → decision → conditions/evidence linkage; standard versioning', 'Accreditation cycle → assessment → decision → conditions'),
  aggregate('A09', 'Document', 'Core', 'The polymorphic document/evidence store with lifecycle.', 'Document Handling (D3 evidence owner)', 'Document', 'Lifecycle state mandatory; soft-delete; physical DELETE blocked; retention rules; RULE 12 evidence residence', 'Document creation → version → lifecycle → disposal/archive'),
  aggregate('A10', 'E-Signature', 'Supporting', 'Digital signing of documents and certificates.', 'Document Handling', 'DigitalCertificate', 'Signature validity; revocation; signature-type registry', 'Certificate issuance → signature → revocation'),
  aggregate('A11', 'Reference', 'Supporting', 'Controlled terminology, catalogs, and knowledge content.', 'Reference Knowledge / Documentation Stewardship', 'ReferenceCatalog', 'Term-gate support (G4); reference data idempotency (Reference Dataset)', 'Vocabulary and catalog lifecycle'),
  aggregate('A12', 'Template', 'Supporting', 'The forms-library / document template engine.', 'Document Handling', 'Template', 'P9/I8: zero consumers — flagged for explicit deprecation/retirement, never silently retained', 'Template library → render jobs (currently unused)'),
  aggregate('A13', 'Communication', 'Supporting', 'Notifications, messages, announcements.', 'Communication Management', 'Message', 'Delivery/read state; recipient routing; preference respect', 'Notification/message dispatch → delivery → read'),
  aggregate('A14', 'Safety', 'Supporting', 'Adverse events, ethics risk, and safety oversight.', 'Safety Governance', 'SafetyReport', 'Adverse-event reporting; ethics-risk assessment linkage; mitigation traceability', 'Incident → assessment → report → follow-up'),
  aggregate('A15', 'Monitoring', 'Supporting', 'Institutional monitoring, inspection, compliance.', 'Oversight', 'MonitoringPlan', 'Inspection → finding → corrective action linkage', 'Monitoring plan → visit → findings → follow-up'),
  aggregate('A16', 'Form', 'Supporting', 'The schema-driven form runtime (engine).', 'Form Runtime (glossary T17)', 'FormDefinition', 'Schema validity; instance integrity', 'Form definition → instance submission'),
  aggregate('A17', 'Institution', 'Supporting', 'Institution and department structure.', 'Institution Administration', 'Institution', 'Org-structure integrity; department membership', 'Institution setup → department → retirement'),
  aggregate('A18', 'Identity', 'Supporting', 'Users, authentication, sessions, profiles.', 'Identity & Access (P2 shared kernel)', 'User', 'Single ownership of identity; session lifecycle; credential handling; never bypassed (I11)', 'Identity creation → authentication → retirement'),
  aggregate('A19', 'AccessControl', 'Supporting', 'Roles, permissions, policy, delegation, segregation.', 'Identity & Access', 'Role', 'Role-permission coherence; segregation rules; approval limits', 'Policy definition → grant → revocation'),
  aggregate('A20', 'Workflow', 'Infrastructure', 'The workflow state machine; RULE 11 reachability source.', 'Workflow Runtime', 'Workflow', 'State reachability (RULE 11 derivation); no orphan transitions; instance runtime', 'Workflow definition → instance → terminal state'),
  aggregate('A21', 'Integration', 'Infrastructure', 'External system connectivity and event plumbing.', 'Integration Runtime', 'ExternalSystem', 'Credential handling; outbox delivery; retry/backoff', 'Integration config → event exchange'),
  aggregate('A22', 'Reporting', 'Infrastructure', 'Derived analytics, KPIs, dashboards.', 'Reporting', 'ReportDefinition', 'Derived-data lifecycle; execution recording', 'Definition → execution → snapshot'),
  aggregate('A23', 'SystemConfiguration', 'Infrastructure', 'System config, feature flags, runtime rules, search, admin ops.', 'Platform Operations', 'SystemConfig', 'Config governance; runtime rule engine distinct from constitutional RULE_* framework', 'Config change → effect → audit'),
  aggregate('A24', 'Audit', 'Infrastructure', 'Immutable audit trail and integrity ledger.', 'Audit', 'AuditLog', 'Append-only immutability; hash ledger integrity; never seeded (I11)', 'Event → audit record → integrity check'),
  aggregate('A25', 'Execution', 'Infrastructure', 'Installer History and execution bookkeeping.', 'Engineering/DevOps Governance (D8)', 'ExecutionRecord', 'Tracker provenance untrusted (P7/A1); historical record, never the dataset (P1/I1)', 'Installer event → record → retention'),
];

export const AGGREGATE_TABLES: ReadonlyArray<AggregateTable> = [
  /* A24 Audit */
  table('A24', 'audit', 'audit_details', 'Audit', 'Runtime-generated'),
  table('A24', 'audit', 'audit_logs', 'Audit', 'Runtime-generated'),
  table('A24', 'audit', 'entity_changes', 'Audit', 'Runtime-generated'),
  table('A24', 'audit', 'hash_ledger', 'Audit', 'Runtime-generated'),
  /* A13 Communication */
  table('A13', 'communication', 'announcements', 'Communication Management', 'Supporting'),
  table('A13', 'communication', 'message_attachments', 'Communication Management', 'Runtime-generated'),
  table('A13', 'communication', 'message_recipients', 'Communication Management', 'Runtime-generated'),
  table('A13', 'communication', 'messages', 'Communication Management', 'Runtime-generated'),
  table('A13', 'communication', 'notification_channels', 'Communication Management', 'Supporting'),
  table('A13', 'communication', 'notification_logs', 'Communication Management', 'Runtime-generated'),
  table('A13', 'communication', 'notification_templates', 'Communication Management', 'Supporting'),
  table('A13', 'communication', 'notifications', 'Communication Management', 'Runtime-generated'),
  table('A13', 'communication', 'user_notification_preferences', 'Communication Management', 'Runtime-generated'),
  /* A16 Form */
  table('A16', 'forms', 'form_definitions', 'Form Runtime', 'Supporting'),
  table('A16', 'forms', 'form_instances', 'Form Runtime', 'Runtime-generated'),
  /* A21 Integration */
  table('A21', 'integration', 'data_sync_jobs', 'Integration Runtime', 'Runtime-generated'),
  table('A21', 'integration', 'event_bus_config', 'Integration Runtime', 'Infrastructure'),
  table('A21', 'integration', 'event_outbox', 'Integration Runtime', 'Runtime-generated'),
  table('A21', 'integration', 'event_subscriptions', 'Integration Runtime', 'Infrastructure'),
  table('A21', 'integration', 'external_systems', 'Integration Runtime', 'Infrastructure'),
  table('A21', 'integration', 'integration_credentials', 'Integration Runtime', 'Infrastructure'),
  table('A21', 'integration', 'integration_failures', 'Integration Runtime', 'Runtime-generated'),
  table('A21', 'integration', 'integration_logs', 'Integration Runtime', 'Runtime-generated'),
  table('A21', 'integration', 'retry_queue', 'Integration Runtime', 'Runtime-generated'),
  table('A21', 'integration', 'webhooks', 'Integration Runtime', 'Infrastructure'),
  /* A15 Monitoring */
  table('A15', 'monitoring', 'compliance_reviews', 'Oversight', 'Supporting'),
  table('A15', 'monitoring', 'corrective_actions', 'Oversight', 'Supporting'),
  table('A15', 'monitoring', 'deviations', 'Oversight', 'Supporting'),
  table('A15', 'monitoring', 'inspection_reports', 'Oversight', 'Supporting'),
  table('A15', 'monitoring', 'inspections', 'Oversight', 'Supporting'),
  table('A15', 'monitoring', 'monitoring_findings', 'Oversight', 'Supporting'),
  table('A15', 'monitoring', 'monitoring_plans', 'Oversight', 'Supporting'),
  table('A15', 'monitoring', 'monitoring_visits', 'Oversight', 'Supporting'),
  table('A15', 'monitoring', 'preventive_actions', 'Oversight', 'Supporting'),
  table('A15', 'monitoring', 'protocol_violations', 'Oversight', 'Supporting'),
  /* A25 Execution */
  table('A25', 'ops', 'seed_tracker', 'Engineering/DevOps Governance (D8)', 'Historical'),
  table('A25', 'public', 'perf_results', 'Engineering/DevOps Governance (D8)', 'Historical'),
  table('A25', 'public', 'pgmigrations', 'Engineering/DevOps Governance (D8)', 'Historical'),
  /* عروض عامة */
  table('A04', 'public', 'v_chair_id', 'Research Ethics Committee', 'View'),
  table('A17', 'public', 'v_inst_codes', 'Institution Administration', 'View'),
  table('A18', 'public', 'v_user_id', 'Identity & Access', 'View'),
  /* A11 Reference */
  table('A11', 'reference', 'academic_titles', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'application_statuses', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'committee_decision_types', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'document_statuses', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'institutions_registry', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'licenses_registry', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'lookup_categories', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'lookup_values', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'notification_statuses', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'priority_levels', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'professions_registry', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'review_statuses', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'risk_levels', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'status_types', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'vote_types', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'reference', 'workflow_statuses', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  /* A22 Reporting */
  table('A22', 'reporting', 'analytics_snapshots', 'Reporting', 'Runtime-generated'),
  table('A22', 'reporting', 'dashboard_widgets', 'Reporting', 'Infrastructure'),
  table('A22', 'reporting', 'kpi_results', 'Reporting', 'Runtime-generated'),
  table('A22', 'reporting', 'report_definitions', 'Reporting', 'Infrastructure'),
  table('A22', 'reporting', 'report_executions', 'Reporting', 'Runtime-generated'),
  /* A14 Safety (schema safety) */
  table('A14', 'safety', 'adverse_events', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'corrective_actions', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'mitigation_actions', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'risk_assessments', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'risk_categories', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'risk_incidents', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'risk_mitigations', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'risk_register', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'safety_committee_reviews', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'safety_followups', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'safety_reports', 'Safety Governance', 'Supporting'),
  table('A14', 'safety', 'serious_adverse_events', 'Safety Governance', 'Supporting'),
  /* A23 SystemConfiguration */
  table('A23', 'system', 'audit_config', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'audit_log', 'Platform Operations', 'Runtime-generated'),
  table('A23', 'system', 'business_rules', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'email_config', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'feature_flags', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'maintenance_log', 'Platform Operations', 'Runtime-generated'),
  table('A23', 'system', 'push_config', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'rule_actions', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'rule_conditions', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'rule_executions', 'Platform Operations', 'Runtime-generated'),
  table('A23', 'system', 'rule_versions', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'saved_searches', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'search_audit', 'Platform Operations', 'Runtime-generated'),
  table('A23', 'system', 'search_indexes', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'sms_config', 'Platform Operations', 'Infrastructure'),
  table('A23', 'system', 'system_config', 'Platform Operations', 'Infrastructure'),
  /* A12 Template (schema templates) */
  table('A12', 'templates', 'categories', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'event_template_mapping', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_approval_workflow', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_localizations', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_outputs', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_package_members', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_packages', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_partials', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_render_history', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_render_jobs', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_usage_statistics', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_validation_tests', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_variables', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_version_audit', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'template_versions', 'Document Handling', 'Dead-data'),
  table('A12', 'templates', 'templates', 'Document Handling', 'Dead-data'),
  /* A20 Workflow */
  table('A20', 'workflow', 'workflow_actions', 'Workflow Runtime', 'Runtime-generated'),
  table('A20', 'workflow', 'workflow_comments', 'Workflow Runtime', 'Runtime-generated'),
  table('A20', 'workflow', 'workflow_escalations', 'Workflow Runtime', 'Runtime-generated'),
  table('A20', 'workflow', 'workflow_events', 'Workflow Runtime', 'Runtime-generated'),
  table('A20', 'workflow', 'workflow_history', 'Workflow Runtime', 'Runtime-generated'),
  table('A20', 'workflow', 'workflow_instances', 'Workflow Runtime', 'Runtime-generated'),
  table('A20', 'workflow', 'workflow_schedulers', 'Workflow Runtime', 'Infrastructure'),
  table('A20', 'workflow', 'workflow_sla', 'Workflow Runtime', 'Infrastructure'),
  table('A20', 'workflow', 'workflow_states', 'Workflow Runtime', 'Infrastructure'),
  table('A20', 'workflow', 'workflow_tasks', 'Workflow Runtime', 'Runtime-generated'),
  table('A20', 'workflow', 'workflow_transitions', 'Workflow Runtime', 'Infrastructure'),
  table('A20', 'workflow', 'workflow_triggers', 'Workflow Runtime', 'Infrastructure'),
  table('A20', 'workflow', 'workflow_variables', 'Workflow Runtime', 'Runtime-generated'),
  table('A20', 'workflow', 'workflows', 'Workflow Runtime', 'Infrastructure'),
  /* A01 Application */
  table('A01', 'core', 'applications', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'application_versions', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'application_history', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'application_amendments', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'amendment_requests', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'renewal_requests', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'closure_requests', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'application_checklists', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'application_sections', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'application_validations', 'Research Ethics Governance', 'Core'),
  table('A01', 'core', 'application_consents', 'Research Ethics Governance', 'Core'),
  /* A03 ResearchProject */
  table('A03', 'core', 'projects', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'project_versions', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'project_team_members', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'project_sites', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'project_site_investigators', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'project_funding_sources', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'project_keywords', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'project_tags', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'project_attachments', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'project_status_history', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'research_categories', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'research_population_links', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'risk_classifications', 'Research Governance Authority', 'Core'),
  table('A03', 'core', 'vulnerable_populations', 'Research Governance Authority', 'Core'),
  /* A04 Committee */
  table('A04', 'committee', 'committees', 'Research Ethics Committee', 'Core'),
  table('A04', 'committee', 'committee_types', 'Research Ethics Committee', 'Core'),
  table('A04', 'committee', 'committee_members', 'Research Ethics Committee', 'Core'),
  table('A04', 'committee', 'committee_member_roles', 'Research Ethics Committee', 'Core'),
  table('A04', 'committee', 'committee_roles', 'Research Ethics Committee', 'Core'),
  table('A04', 'committee', 'member_terms', 'Research Ethics Committee', 'Core'),
  table('A04', 'committee', 'member_qualifications', 'Research Ethics Committee', 'Core'),
  table('A04', 'committee', 'member_conflicts', 'Research Ethics Committee', 'Core'),
  /* A05 Meeting */
  table('A05', 'committee', 'committee_meetings', 'Research Ethics Committee', 'Core'),
  table('A05', 'committee', 'meeting_agendas', 'Research Ethics Committee', 'Core'),
  table('A05', 'committee', 'agenda_items', 'Research Ethics Committee', 'Core'),
  table('A05', 'committee', 'attendance_logs', 'Research Ethics Committee', 'Core'),
  table('A05', 'committee', 'quorum_logs', 'Research Ethics Committee', 'Core'),
  table('A05', 'committee', 'voting_sessions', 'Research Ethics Committee', 'Core'),
  table('A05', 'committee', 'votes', 'Research Ethics Committee', 'Core'),
  table('A05', 'committee', 'meeting_minutes', 'Research Ethics Committee', 'Core'),
  /* A06 Review */
  table('A06', 'committee', 'ethics_reviews', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'scientific_reviews', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'review_assignments', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'review_forms', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'review_questions', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'review_answers', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'review_scores', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'review_comments', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'review_recommendations', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'review_conflicts', 'Research Ethics Committee', 'Core'),
  table('A06', 'committee', 'consent_review_comments', 'Research Ethics Committee', 'Core'),
  /* A02 Condition */
  table('A02', 'committee', 'application_conditions', 'Research Ethics Governance', 'Core'),
  /* A08 Accreditation */
  table('A08', 'committee', 'accreditation_assessment_items', 'Research Governance Authority', 'Supporting'),
  table('A08', 'committee', 'accreditation_assessments', 'Research Governance Authority', 'Supporting'),
  table('A08', 'committee', 'accreditation_conditions', 'Research Governance Authority', 'Supporting'),
  table('A08', 'committee', 'accreditation_cycle_metrics', 'Research Governance Authority', 'Supporting'),
  table('A08', 'committee', 'accreditation_cycles', 'Research Governance Authority', 'Supporting'),
  table('A08', 'committee', 'accreditation_decisions', 'Research Governance Authority', 'Supporting'),
  table('A08', 'committee', 'accreditation_evidence', 'Research Governance Authority', 'Supporting'),
  table('A08', 'committee', 'accreditation_standard_versions', 'Research Governance Authority', 'Supporting'),
  table('A08', 'committee', 'accreditation_standards', 'Research Governance Authority', 'Supporting'),
  /* A14 Safety (schema committee) */
  table('A14', 'committee', 'ethics_risk_assessments', 'Safety Governance', 'Supporting'),
  table('A14', 'committee', 'ethics_risk_items', 'Safety Governance', 'Supporting'),
  /* A11 Reference (schema committee) */
  table('A11', 'committee', 'consent_templates', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  table('A11', 'committee', 'consent_template_versions', 'Reference Knowledge / Documentation Stewardship', 'Reference-data'),
  /* A09 Document */
  table('A09', 'documents', 'documents', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_versions', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_access', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_approvals', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_audit', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_classifications', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_disposal_logs', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_lifecycle_states', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_lifecycle_transitions', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_numbering', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_retention_rules', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_types', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_watermark_config', 'Document Handling', 'Core'),
  table('A09', 'documents', 'document_verification_log', 'Document Handling', 'Core'),
  /* A07 Approval */
  table('A07', 'documents', 'approval_certificates', 'Research Ethics Governance', 'Core'),
  table('A07', 'documents', 'approval_certificate_documents', 'Research Ethics Governance', 'Core'),
  table('A07', 'documents', 'certificate_verification_log', 'Research Ethics Governance', 'Core'),
  /* A10 E-Signature (schema documents) */
  table('A10', 'documents', 'document_signatures', 'Document Handling', 'Supporting'),
  table('A10', 'documents', 'document_signature_types', 'Document Handling', 'Supporting'),
  /* A12 Template (schema documents) */
  table('A12', 'documents', 'templates', 'Document Handling', 'Dead-data'),
  table('A12', 'documents', 'generated_documents', 'Document Handling', 'Dead-data'),
  /* A18 Identity */
  table('A18', 'security', 'users', 'Identity & Access', 'Runtime-generated'),
  table('A18', 'security', 'user_profiles', 'Identity & Access', 'Runtime-generated'),
  table('A18', 'security', 'user_roles', 'Identity & Access', 'Runtime-generated'),
  table('A18', 'security', 'user_responsibilities', 'Identity & Access', 'Runtime-generated'),
  table('A18', 'security', 'sessions', 'Identity & Access', 'Runtime-generated'),
  table('A18', 'security', 'login_audit', 'Identity & Access', 'Runtime-generated'),
  table('A18', 'security', 'api_keys', 'Identity & Access', 'Runtime-generated'),
  table('A18', 'security', 'email_verification_tokens', 'Identity & Access', 'Runtime-generated'),
  table('A18', 'security', 'password_reset_tokens', 'Identity & Access', 'Runtime-generated'),
  table('A18', 'security', 'password_history', 'Identity & Access', 'Runtime-generated'),
  /* A19 AccessControl */
  table('A19', 'security', 'roles', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'role_permissions', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'permissions', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'role_delegations', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'access_policies', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'policy_rules', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'policy_conditions', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'responsibility_types', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'segregation_rules', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'security_events', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'approval_authorities', 'Identity & Access', 'Supporting'),
  table('A19', 'security', 'approval_limits', 'Identity & Access', 'Supporting'),
  /* A10 E-Signature (schema security) */
  table('A10', 'security', 'digital_certificates', 'Document Handling', 'Supporting'),
  table('A10', 'security', 'certificate_revocations', 'Document Handling', 'Supporting'),
  /* A17 Institution */
  table('A17', 'security', 'institutions', 'Institution Administration', 'Supporting'),
  table('A17', 'security', 'institution_types', 'Institution Administration', 'Supporting'),
  table('A17', 'security', 'departments', 'Institution Administration', 'Supporting'),
];

export const OWNERSHIP_REGISTRY = new ConstitutionalRegistry<AggregateTable>(
  'R10',
  'Ownership Registry',
  'D3',
  [
    { document: 'DOMAIN_MODEL.md', section: 'Section 1 (25 aggregates)' },
    { document: 'architecture/aggregate-table-mapping.csv', section: '234 tables' },
    { document: 'ADR-002', section: 'P2 / I4 / G5' },
  ],
  AGGREGATE_TABLES,
);
